# Generated by Django 5.2 on 2025-06-10 14:17

import django.db.models.deletion
import permissions.permissions
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': ((permissions.permissions.Permissions['VIEW'], 'View Project'), (permissions.permissions.Permissions['UPDATE'], 'Update Project'), (permissions.permissions.Permissions['DELETE'], 'Delete Project'), (permissions.permissions.Permissions['CREATE_TASK'], 'Create Task')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('status', models.CharField(choices=[(projects.models.StatusChoice['TO_DO'], 'TO DO'), (projects.models.StatusChoice['IN_PROGRESS'], 'IN PROGRESS'), (projects.models.StatusChoice['REVIEW'], 'REVIEW'), (projects.models.StatusChoice['DONE'], 'DONE')], default=projects.models.StatusChoice['TO_DO'], max_length=2)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'permissions': ((permissions.permissions.Permissions['VIEW'], 'View Task'), (permissions.permissions.Permissions['UPDATE'], 'Update Task'), (permissions.permissions.Permissions['DELETE'], 'Delete Task')),
                'default_permissions': (),
            },
        ),
    ]
