# Generated by Django 5.2 on 2025-05-16 15:37

import django.db.models.deletion
import projects.permissions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    (projects.permissions.Permissions["VIEW_PROJECT"], "View Project"),
                    (
                        projects.permissions.Permissions["UPDATE_PROJECT"],
                        "Update Project",
                    ),
                    (
                        projects.permissions.Permissions["DELETE_PROJECT"],
                        "Delete Project",
                    ),
                ),
                "default_permissions": (),
            },
        ),
    ]
