# Generated by Django 5.2 on 2025-05-20 18:49

import django.db.models.deletion
import projects.models
import projects.permissions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'default_permissions': (), 'permissions': ((projects.permissions.Permissions['VIEW_PROJECT'], 'View Project'), (projects.permissions.Permissions['UPDATE_PROJECT'], 'Update Project'), (projects.permissions.Permissions['DELETE_PROJECT'], 'Delete Project'), (projects.permissions.Permissions['CREATE_TASK'], 'Create Task'))},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('status', models.CharField(choices=[(projects.models.StatusChoice['TO_DO'], 'TO DO'), (projects.models.StatusChoice['IN_PROGRESS'], 'IN PROGRESS'), (projects.models.StatusChoice['REVIEW'], 'REVIEW'), (projects.models.StatusChoice['DONE'], 'DONE')], default=projects.models.StatusChoice['TO_DO'], max_length=2)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'permissions': ((projects.permissions.Permissions['VIEW_TASK'], 'View Task'), (projects.permissions.Permissions['UPDATE_TASK'], 'Update Task'), (projects.permissions.Permissions['DELETE_TASK'], 'Delete Task')),
                'default_permissions': (),
            },
        ),
    ]
