# Generated by Django 5.2 on 2025-06-24 16:04

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('read_model', django.db.models.manager.Manager()),
            ],
        ),
    ]
