# Generated by Django 5.2 on 2025-07-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_task_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='pending_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
